CREATE TABLE IF NOT EXISTS `pan_containers` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`label` LONGTEXT NULL DEFAULT NULL,
	`coords` LONGTEXT NULL DEFAULT NULL,
	`heading` LONGTEXT NULL DEFAULT NULL,
	`target` LONGTEXT NULL DEFAULT NULL,
	`lastupdated` TIMESTAMP NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
	`isdeleted` TINYTEXT NOT NULL DEFAULT 'false',
	PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8mb3_general_ci;